M48
; DRILL file {KiCad 9.0.3} date 2026-01-13T08:46:25+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-13T08:46:25+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X120.185Y-60.56
X125.035Y-60.56
T2
X119.885Y-57.53
X125.335Y-57.53
T3
X111.0Y-54.5
X111.5Y-108.5
X154.5Y-108.5
X155.0Y-54.5
T4
X145.0Y-59.995
M30
